module Myparcel
  module API
    # Class for managing tracktraces
    class Tracktraces < Myparcel::API::Base
      def find(options = {})
        language = options.fetch(:language, :nl)
        raise 'options[:language] must be one of [:nl, :en]' unless [:en, :nl].include?(language)
        shipment_ids = options.fetch(:shipment_ids, [])
        raise 'options[:shipment_ids] cannot be empty' if shipment_ids.empty?
        shipment_ids = shipment_ids.join(';')
        full_path = [path, shipment_ids].join('/')
        response = request :get, full_path, options
        tracktraces = response['data']['tracktraces']

        # For some reason empty tracktraces are represented as [[]] by MyParcel
        if tracktraces == [[]]
          return []
        end

        if language == :nl
          tracktraces
        else
          tracktraces.map { |tracktrace| translate(language, tracktrace) }
        end
      end

      def path
        'tracktraces'
      end

      private

      def translate(language, tracktrace)
        codemap = POSTNL_STATUS_CODES.fetch(language)
        tracktrace.update(
          "description" => codemap[tracktrace["code"]],
          "history" => tracktrace["history"].map { |hist| hist.update("description" => codemap.fetch(hist["code"])) }
        )
      end

      POSTNL_STATUS_CODES = {
        en: {
          "A10"  => "Sender created return label",
          "B01" => "Shipment received by PostNL",
          "C01" => "Shipment collected by PostNL",
          "D01" => "Pick-up shipment not collected; refused at pick-up address",
          "D02" => "Pick-up shipment not collected due to relocation",
          "D03" => "Pick-up shipment not collected; no one present at address",
          "D04" => "Pick-up shipment not collected; wrong address",
          "D05" => "Pick-up shipment not collected; shipment not present",
          "D08" => "No response at 1st pick-up attempt, 2nd attempt next working day",
          "D33" => "No response at 3rd pick-up attempt, pick-up order expires",
          "F01" => "Pick-up shipment is collected",
          "F02" => "Pick-up shipment is collected",
          "F03" => "Shipment not processed due to missing shipping information",
          "F04" => "Shipment not processed due to missing shipping information",
          "F05" => "Shipment not processed. Missing pick-up contract.",
          "F06" => "Shipment not processed. Postal code of collection address is unknown.",
          "F07" => "Shipment not processed. Postal code of delivery address is unknown.",
          "F08" => "Shipment not processed. Collection date is in the past.",
          "F09" => "Shipment offered too late. Collection date next business day.",
          "F10" => "Shipment not processed. Collection date is not a business day.",
          "F12" => "Collection order not processed, no collection service available",
          "F13" => "Collection order not processed, collection date too far in future",
          "G01" => "Shipment not yet processed.",
          "H01" => "Shipment refused by addressee. Return to Sender",
          "H02" => "Shipment return to Sender, address unknown",
          "H03" => "Shipment return to Sender. Not picked up as PostNL location.",
          "H04" => "Shipment is damaged. Return to Sender.",
          "H05" => "Shipment will return to Sender in accordance with the agreement.",
          "H06" => "Exchange could not be delivered to the addressee.",
          "H07" => "Shipment not delivered after 2 attempts. Return to Sender",
          "H12" => "Shipment return to Sender, addressee unknown",
          "H34" => "Shipment not delivered, PostNL contacts the sender.",
          "H77" => "Shipment not delivered after 3 attempts. Return to Sender",
          "I01" => "Shipment delivered",
          "I02" => "Shipment picked up at PostNL location",
          "I03" => "Shipment delivered",
          "I04" => "Shipment delivered",
          "I05" => "Shipment delivered",
          "I06" => "Shipment delivered",
          "I07" => "Return shipment transferred to sender",
          "I08" => "Shipment available at PostNL location",
          "I09" => "Shipment delivered",
          "I10" => "Shipment delivered with neighbors",
          "I11" => "Shipment is mailbox",
          "I20" => "Available for mail box holder",
          "J01" => "Shipment sorted in sorting center",
          "J02" => "Shipment available at PostNL location",
          "J03" => "Shipment still in sorting process",
          "J05" => "Out for delivery",
          "J06" => "Shipment sorted in sorting center",
          "J07" => "Closed: delivery postponed to next business day",
          "J08" => "First delivery attempt failed. Second attempt follows",
          "J09" => "Episode postponed until next working day",
          "J10" => "Receive shipment at distribution site",
          "J11" => "Shipment available at PostNL location",
          "J12" => "Shipment available at PostNL location",
          "J13" => "Shipment is in delivery route",
          "J14" => "Shipment still in sorting process; episode 1 day delayed",
          "J16" => "Delivery address unreachable, new attempt to follow",
          "J17" => "Episode postponed due to closed statement",
          "J20" => "Out for delivery",
          "J24" => "Delivery postponed until next business day",
          "J25" => "Delivery delayed due to weather conditions",
          "J26" => "Delivery delayed due to traffic conditions",
          "J30" => "Shipment taken by Plan desk",
          "J61" => "Shipment sorted for destination country",
          "J80" => "Time-critical shipment not yet scanned for delivery",
          "J88" => "2nd delivery attempt failed; 3rd delivery attempt follows",
          "K01" => "Shipment still in sorting process; delivery delayed for 1 day",
          "K02" => "Addressee has moved. Shipment forwarded to new address",
          "K03" => "Shipment forwarded to address chosen by the addressee",
          "K04" => "Shipment available next business day at PostNL location",
          "K05" => "Addressee absent. Shipment is at the stated location.",
          "K06" => "Shipment is again in delivery route",
          "K07" => "Shipment is available at PostNL location",
          "K08" => "Shipment is available at PostNL location",
          "K09" => "Shipment is available at PostNL location",
          "K10" => "Shipment not delivered, sender unknown",
          "K11" => "Shipment still in sorting process; delivery delayed for 1 day",
          "K12" => "Return PostNL",
          "K13" => "Shipment insufficiently franked; shipment 1 day delayed",
          "K14" => "1st delivery attempt failed. 2nd delivery attempt follows",
          "K15" => "Error in delivery. Further information follows.",
          "K16" => "Freight shipment not delivered; addressee absent.",
          "K17" => "Shipment not delivered",
          "K18" => "Shipment not delivered",
          "K24" => "Shipment is delivered on request at a PostNL location",
          "K25" => "Shipment is delivered on request at a PostNL location",
          "K30" => "Shipment is traced but can not be delivered",
          "K31" => "Your shipment is no longer available",
          "K70" => "Shipment is delivered to PostNL location",
          "K72" => "Shipment available at PostNL location",
          "K80" => "Shipment forwarded to sorting center",
          "K85" => "Incident notification made",
          "K90" => "No status known yet. Try again later.",
          "M01" => "Shipment not physically offered to PostNL",
          "M02" => "Pre-reported shipment not found: shortage",
          "R01" => "Shipment sorted in sorting center",
          "S01" => "Shipment sorted in sorting center",
          "S02" => "Out for delivery",
          "S05" => "Shipment is in delivery route",
          "S07" => "Delivery postponed until next working day",
          "S13" => "Shipment is in delivery route",
          "S20" => "Shipment is in delivery route",
          "T01" => "Delivery of shipment has been postponed until next working day.",
          "V01" => "Received by PostNL, delayed",
          "V06" => "Shipment not yet sorted. Delivery on next business day.",
          "X01" => "Sent to destination country",
          "X02" => "Received in country of destination",
          "X03" => "Customs clearance of the shipment is handled",
          "X04" => "Release by customs",
          "X05" => "Shipment available at PostNL location",
          "X06" => "Shipment is in delivery route",
          "X07" => "Shipment sorted",
          "X08" => "Shipment in depot",
          "X50" => "Shipment in depot",
          "X51" => "Shipment sorted",
          "X55" => "Out for delivery to PostNL location",
          "X80" => "Pick-up order collected",
          "X81" => "Return shipment received at post office",
          "Y01" => "Shipment not delivered. Address incorrect",
          "Y02" => "Shipment not delivered. Addressee absent",
          "Y03" => "Shipment has been rejected by the addressee.",
          "Y04" => "Shipment was not delivered due to damage",
          "Y05" => "Out for delivery",
          "Y06" => "Shipment incorrectly addressed. 2nd delivery attempt follows.",
          "Y07" => "Shipment still in sorting process; delivery 1 day delayed",
          "Y08" => "Delivery 1 business day postponed due to national holiday",
          "Y09" => "Contact with addressee due to incorrect delivery address",
          "Y10" => "First delivery attempt failed. Second attempt follows",
          "Y11" => "Shipment is damaged. Contact with addressee",
          "Y12" => "Contact with sender due to incorrect delivery address",
          "Y13" => "Refused by addressee. Contact with sender",
          "Y14" => "Shipment is damaged. Contact with sender",
          "Y15" => "Shipment not delivered. Contact with sender",
          "Y16" => "Shipment not delivered; address incorrect. Return to Sender",
          "Y17" => "Recipient is not known at this address",
          "Y18" => "Shipment is damaged. Return to Sender",
          "Y19" => "Shipment not delivered; prohibited article. Return to Sender",
          "Y20" => "Shipment not picked up at PostNL location. Return to Sender",
          "Y21" => "Return to Sender",
          "Y22" => "Shipment not delivered, the addressee moved.",
          "Y23" => "Address corrected. New delivery attempt",
          "Y24" => "Address corrected. New delivery attempt",
          "Y25" => "Shipment is at customs for further processing",
          "Y26" => "Shipment delivered in mailbox",
          "Y28" => "Shipment is released by customs",
          "Y30" => "Shipment has not been delivered due to incorrect zip code.",
          "Y31" => "Shipment has not been delivered. Zip code is missing.",
          "Y32" => "Shipment has not been delivered. Adress unknown.",
          "Y40" => "Last delivery attempt failed. Return to Sender",
          "Y41" => "Shipment has not been delivered. Access code location is missing",
          "Y42" => "Shipment has not been delivered. Addressee is unreachable.",
          "Y43" => "Shipment not delivered. Location of the recipient closed.",
          "Y50" => "Shipment refused; incomplete",
          "Y60" => "Shipment delayed due to circumstances",
          "Y61" => "Shipment delayed due to weather conditions",
          "Y62" => "Delay due to transport and / or traffic problems",
          "Y71" => "Shipment is missing",
          "Y80" => "Collection order failed. 2nd attempt next business day.",
          "Y81" => "Collection order failed, no new attempt",
          "Z01" => "Shipment delivered",
          "Z1" => "Shipment delivered",
          "Z02" => "Shipment delivered to destination address",
          "Z2" => "Shipment delivered to destination address",
          "Z03" => "Shipment delivered to destination address",
          "Z3" => "Shipment delivered to destination address",
          "Z04" => "Shipment delivered to destination address",
          "Z4" => "Shipment delivered to destination address",
          "Z05" => "Shipment delivered with neighbors",
          "Z5" => "Shipment delivered with neighbors",
          "Z06" => "Shipment picked up at PostNL location",
          "Z6" => "Shipment picked up at PostNL location",
          "Z80" => "Pick-up attempt successful",
          # additional codes
          "A01" => "Shipment is registered with PostNL and can be followed",
          "J93" => "Shipment partially not encountered",
          "D40" => "Shipment not collected",
          "D41" => "Collection shipment canceled",
          "H31" => "Shipment was canceled by sender",
          "H37" => "Shipment not picked up; adress unknown. PostNL calls the sender",
          "A03" => "Notification created by PostNL",
          "J27" => "Shipment sorted by depot",
          "A12" => "Choice of recipient: delivery on another day",
          "A42" => "Delivery date of the shipment has been adjusted.",
          "A43" => "E-mail sent with invitation for 2nd delivery attempt.",
          "H32" => "Shipment not delivered; lack of space. Delivery postponed",
          "H35" => "Shipment is damaged. PostNL contacts the sender",
          "J19" => "Notified and scanned on ride",
          "Q01" => "Shipment is registered and can be followed",
          "Q11" => "Package attached to packing material",
          "Q12" => "Shipment put on transport",
          "H09" => "Shipment incomplete. Return to Sender",
          "H22" => "Shipment was canceled after transfer to PostNL.",
          "H36" => "Shipment not delivered; adress unknown. PostNL calls the sender",
          "J43" => "Offered outside the time window and recipient not at home.",
          "J64" => "Implicit relabel scan",
          "J92" => "Shipment not delivered; lack of time",
          "K41" => "Cash on delivery no delivered, recipient cannot pay",
          "K43" => "Shipment is returned",
          "J91" => "Partially delivered shipment Y26 Shipment delivered in mailbox",
          "A05" => "Notified, not accepted",
          "H23" => "Canceled by PostNL, can not make a delivery appointment.",
          "V11" => "Received by PostNL, delayed V13 Received by PostNL",
          "V21" => "Received by PostNL, delayed V50 Received by PostNL",
          "A18" => "Initial calculation of ETA",
          "A19" => "ETA changed",
          "A40" => "E-mail with the delivery date confirmation has been sent.",
          "A41" => "CS Extra @ Home has had contact with the recipient.",
          "A44" => "E-mail with link to track & trace has been sent.",
          "A90" => "Notification pick-up location Lagardère",
          "J47" => "Package from Package Vending Machine to nearest pickup location"
        }
      }
    end
  end
end
